### PR TITLE
Fix missing parents in platform example

### PR DESCRIPTION
**Pull request by cbullo**

### CODE REVIEW

**Comment by glencoe** [comment]
Hi,

thanks for your pull request!
What is your reasoning behind removing the c99 feature?

**Comment by tomasz-cybulski-oqton** [comment]
Oh, that's a mistake on my part - I didn't want removal of c99 flag to be part of this PR.
I only wanted to update the documentation.
I removed c99 flag on my end to compile C++ code without a warning.

**Comment by tomasz-cybulski-oqton** [comment]
Feel free to only update the docs

**Comment by glencoe** [comment]
You can disable a feature in this case "gnu99" by using

https://docs.bazel.build/versions/master/command-line-reference.html#flag--features

However we should document how that feature is called and that we enable it by default.

**Comment by cbullo** [comment]
Oh, that's a mistake on my part - I didn't want removal of c99 flag to be part of this PR.
I only wanted to update the documentation.
I removed c99 flag on my end to compile C++ code without a warning.

**Comment by cbullo** [comment]
> You can disable a feature in this case "gnu99" by using
> 
> https://docs.bazel.build/versions/master/command-line-reference.html#flag--features
> 
> However we should document how that feature is called and that we enable it by default.

Thank you for the link. I'll keep the change on my end, as I will develop in C++ mostly.

**Comment by glencoe** [comment]
For future reference... people not happy with that feature being enabled by default can use the
`.bazelrc` config file to disable it permamently.

**Comment by glencoe** [comment]
I'll close this as the missing parents platform was already fixed from our side. And our current BUILD.tpl is tested and i doubt that including these into the pull request was inteded.

**Comment by cbullo** [comment]
@glencoe it's fine that you closed it, I forgot that it was still open. However, I do think you have a bug in avrdude_upload_script - wrong argument tags and non-closed " .

**Pull request closed without merging**
